version: 0.2

phases:
  install:
    commands:
      - echo  install phase
  pre_build:
    commands:
      - printenv
      - npm install
      - echo "//registry.npmjs.org/:_authToken=$npmToken" > .npmrc
      - echo "@gsat:registry=https://registry.npmjs.org/" >> .npmrc
      - echo "scope=gsat" >> .npmrc
      - echo ".npmrc file content" ; cat .npmrc
  build:
    commands:
      - npm run lint
      - npm run test
      - #node cicd/build_number.js $buildNum
      - npm publish --access public
      - npm run storybook-static
      - aws s3 cp --recursive storybookstatic/ s3://$storybookBucket
  post_build:
    commands:
      - echo postbuild phase
artifacts:
  files:
    - storybookstatic/**/*

